### PR TITLE
Update arcs when nrOfLevels arcsLength or colors change

### PR DESCRIPTION
**Pull request by Thebarda**

### CODE REVIEW

**Comment by Thebarda** [comment]
This PR should fix #22

**Comment by Martin36** [comment]
I tried to fix the merge conflicts the but new chart won't render properly.

**Comment by Martin36** [comment]
@Thebarda Please see the branch "Thebarda-update_arcs_when_nrOfLevels_arcsLength_or_colors_change" and see if can fix the rendering of the chart.

**Comment by Martin36** [comment]
Merged :)

**Pull request closed without merging**
