### PR TITLE
fix defaultProps deprecation warning

### PR DESCRIPTION
**Pull request by zwhitchcox**
Fixes warning

>`app-index.js:31 Warning: GaugeChart: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`

### CODE REVIEW

**Comment by zwhitchcox** [comment]
In the meantime, if anyone else needs it https://npmjs.com/@zwhitchcox/react-gauge-chart

**Comment by Martin36** [comment]
There is some conflicts in this PR. If you fix them I will merge it

**Comment by iklein99** [comment]
Do we expect this to be resolved soon?

**Comment by rsolomon** [comment]
Howdy @Martin36 , I've opened #151 that aims to accomplish the same thing as #139 . It should be in a ready-to-merge state if you wouldn't mind taking a look. Hope all is well!

**Comment by Martin36** [comment]
@rsolomon Thanks! Your PR is merged now

**Pull request closed without merging**
