### PR TITLE
feat: added custom text component

### PR DESCRIPTION
**Pull request by kashaudhan**
Added custom component as request #129

### CODE REVIEW

**Comment by kashaudhan** [comment]
Hey @Martin36  could you please merge this pr. This is required for us to continue.

**Comment by Martin36** [comment]
> Hey @Martin36 could you please merge this pr. This is required for us to continue.

Hey, if you fix the conflicts I will merge it

**Comment by kashaudhan** [comment]
Hey @Martin36, I have resolved the above conflicts.

**Comment by kashaudhan** [comment]
@Martin36 can you merge it now.

**Pull request merged**
