### PR TITLE
Disable animation option

### PR DESCRIPTION
**Pull request by nero408**
Solution for #14 
Added property to disable animation, updated Readme and added an example with disabled animation. Default Setting is enabled

### CODE REVIEW

**Comment by beevelop** [comment]
@Martin36 This looks quite useful. What do you think?

**Comment by bastian1993** [comment]
Yes please! Would make it a lot more usable.

**Comment by Martin36** [comment]
@beevelop Sorry for the late reply. I will look at this

**Comment by Martin36** [comment]
Merged this feature now

**Comment by beevelop** [comment]
Thank you for merging!

**Pull request merged**
